[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"
broadcast = "broadcast"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.20"

# Optional: Show gas reports and warnings
ffi = true
via_ir = false
verbosity = 2
